import Head from "next/head";
import Main from "@/components/Main";

function Home() {
  return (
    <>
      <Head>
        <title>MyWeather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main>
        <Main></Main>
      </main>
    </>
  );
}

export default Home;
